#JAIME HERNÁNDEZ DELGADO 48776654W

OPTS = -Wall -O3 -std=c++0x

mcp: mcp_greedy.cc
	g++ ${OPTS} -o mcp_greedy mcp_greedy.cc

tar: mcp_greedy.cc makefile
	tar cvfz 48776654W.tar.gz mcp_greedy.cc makefile
